### PR TITLE
Fix the issue #16

### LINKED ISSUE #16: Call destroy_all after 'where' to has_many associated member , ArgumentError has raised.
Hi.
I"m using this gem instead of acts as paranoid on Rails 4.1.7.
This gem is very useful, Thanks:)

By the way,  I found the issue on calling destroy_all after 'where'.
You can reproduce this issue on this [repo](https://github.com/syguer/sandbox_kakurenbo_bugfix).
And I've created a patch to avoid this issue.
Please check it.

Regards.

P.S
I think this patch looks bad resolver because it can't do exhaustive test and lose maintenability.
It might be hard way that adding options to argument...

### PR DESCRIPTION
**Pull request by syguer**
Fix #16

### CODE REVIEW

**Comment by alfa-jpn** [comment]
Sorry for the late reply.
Thanks for great PR!

**Comment by syguer** [comment]
Thanks to merge!
plz tagging and release too :p

**Comment by alfa-jpn** [comment]
I will release it with other bug fixes.
Please wait for a few days.

**Comment by syguer** [comment]
OK :D

**Pull request merged**
